apiVersion: v1
kind: Service
metadata:
  name: mysql-servicio
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer  # Cambiado de ClusterIP a LoadBalancer